### PR TITLE
Fix binder exception when restoring a large number of applications

### LINKED ISSUE #165: Option to back up all apps by pretending to be a device to device transport
Seedvault is bound to Android's backup API which allows apps to exclude themselves from getting backed up. We want to implement another backup mechanism that will allow us to backup more apps by using an API loophole: pretending to do a device-to-device backup.

* [ ] Handle a larger number of apps getting backed up in a single backup pass
* [ ] Warn about insufficient storage space on backup medium (more likely when backing up more apps without storage quota)
* [ ] Pretend (to the system) to do a device-to-device backup run instead of cloud backups

---

Android 11 ignores the `allowBackup` manifest attribute for device to device transfers (https://developer.android.com/about/versions/11/behavior-changes-11#device-to-device-file-transfer). That means the local backup transport supports it in principle and the apps must support it in principle too. I think it would be a nice addition to Seedvault to make this behavior a (configurable) option. If this is indeed possible of course. This is partly related to #36.

### PR DESCRIPTION
**Pull request by stevesoltys**
Copy of #484 with review comment changes.

### CODE REVIEW

**Comment by grote** [comment]
Awesome work! This looks a lot better than the previous attempt at fixing this. There's still some ktlint style complaints to fix. I'll also run this through manual tests before merging (as this is a rather critical code path).

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt [hunk 1]
```diff
@@ -200,19 +204,13 @@ internal class RestoreViewModel(
...
-            val restoreAllResult = session.restoreAll(token, observer, monitor)
-            if (restoreAllResult != 0) {
-                Log.e(TAG, "restoreAll() returned non-zero value")
-                mRestoreBackupResult.postValue(
-                    RestoreBackupResult(app.getString(R.string.restore_finished_error))
-                )
-            }
-        }
+        // We need to retrieve the restore sets before starting the restore.
+        // Otherwise, restorePackages() won't work as they need the restore sets cached internally.
```
Comment (grote) [inline app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt]: Since you've edited this, I guess you've tested this and even for `restorePackages()`, we need to request the RestoreSet before?

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt [hunk 2]
```diff
@@ -200,19 +204,13 @@ internal class RestoreViewModel(
...
+        val packages = mChosenRestorableBackup.value?.packageMetadataMap?.keys?.toList()
+            ?: emptyList()
```
Comment (grote) [inline app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt]: Does it make sense to continue with an empty list here? Should we fail with an error instead? Can it happen that we don't get the list of packages? If so, when?

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt [hunk 3]
```diff
@@ -307,7 +317,28 @@ internal class RestoreViewModel(
...
+         */
+        private fun restoreNextPackages() {
+            val chunkSize = (packageIndex + PACKAGES_PER_CHUNK).coerceAtMost(packages.size)
+            val packageChunk = packages.subList(packageIndex, chunkSize).toTypedArray()
+            packageIndex += packageChunk.size
+
+            val result = session.restorePackages(token, this, packageChunk, monitor)
+
+            if (result != 0) {
+                Log.e(TAG, "restorePackages() returned non-zero value")
```
Comment (grote) [inline app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt]: This is nothing we need to surface to the user? Should we also log the result?

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt [hunk 4]
```diff
@@ -341,6 +372,13 @@ internal class RestoreViewModel(
          *   as a whole failed.
          */
         override fun restoreFinished(result: Int) {
+
+            // Restore next chunk if successful and there are more packages to restore.
+            if (result == 0 && packageIndex < packages.size) {
```
Comment (grote) [inline app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt]: If the result isn't `0`, should we still try to restore the other packages at least? Btw. is there a constant we can use in place of `0`?

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt [hunk 5]
```diff
@@ -200,19 +204,13 @@ internal class RestoreViewModel(
             return
         }
 
-        // we need to retrieve the restore sets before starting the restore
-        // otherwise restoreAll() won't work as they need the restore sets cached internally
-        val observer = RestoreObserver { observer ->
-            // this lambda gets executed after we got the restore sets
-            // now we can start the restore of all available packages
-            val restoreAllResult = session.restoreAll(token, observer, monitor)
```
Comment (grote) [inline app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt:208]: Are we sure that our list of packages is equivalent to this `restoreAll()` call? Nothing is missing?

**Review by grote — CHANGES_REQUESTED** [review]
Maybe a way to test this could be to install  looooots of apps on the test device and then test with and without this PR applied.

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt (hunk 1 above)
Comment (stevesoltys) [reply app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt]: I haven't tested without requesting the restore set, but I think it's likely to be the same, I can test without it once and see if the tests break to confirm.

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt (hunk 2 above)
Comment (stevesoltys) [reply app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt]: Fails with an error now.

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt (hunk 3 above)
Comment (stevesoltys) [reply app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt]: Error handling will go in the `restoreFinished` function which should always be called after this. Not sure if we even need to log this tbh.

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt (hunk 4 above)
Comment (stevesoltys) [reply app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt]: Changed to constant, keeps going onto the next chunk if we fail.

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt (hunk 5 above)
Comment (stevesoltys) [reply app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt:208]: This I'm not sure of. But I figure we only can restore packages that are in the backup anyways?

**Comment by grote** [comment]
I could reproduce the issue that this MR is fixing by installing more than 500 apps:

```ruby
2023-11-14 11:17:54.932  1522-2762  BackupManagerService    pid-1522                             I  Full restore; asking about 515 apps
2023-11-14 11:17:54.942  1522-2762  BackupManagerService    pid-1522                             D  Starting restore.
2023-11-14 11:17:54.943  1522-2762  BackupRestoreController pid-1522                             I  System restore starting for user: 0
2023-11-14 11:17:54.948 10154-10154 Configurab...ortService com.stevesoltys.seedvault            D  Service created.
2023-11-14 11:17:54.953 10154-10154 Configurab...ortService com.stevesoltys.seedvault            D  Transport bound.
2023-11-14 11:17:54.956  1522-1522  TransportConnection     pid-1522                             I  ConfigurableBackupTransportService#1453: Notifying [PerformUnifiedRestoreTask.startRestore()] transport = BackupTransportClient
2023-11-14 11:17:54.969  1522-2762  BpBinder                pid-1522                             W  Large outgoing transaction of 826056 bytes, interface descriptor , code 14
2023-11-14 11:17:54.969  1522-2762  JavaBinder              pid-1522                             E  !!! FAILED BINDER TRANSACTION !!!  (parcel size = 826056)
2023-11-14 11:17:54.970  1522-2762  BackupManagerService    pid-1522                             E  Unable to contact transport for restore: data parcel size 826056 bytes
2023-11-14 11:17:15.769  2762-2762  binder                  pid-2762                             I  1522:2762 transaction failed 29201/-28, size 826056-8 line 3360
2023-11-14 11:17:54.971 10154-10211 RestoreCoordinator      com.stevesoltys.seedvault            D  finishRestore
2023-11-14 11:17:54.972  1522-2762  BackupRestoreController pid-1522                             I  systemRestoreFinished for 0
2023-11-14 11:17:54.972  1522-2762  BackupRestoreController pid-1522                             I  maybeSendWidgetRestoreBroadcasts for 0
2023-11-14 11:17:54.972  1522-2762  BackupManagerService    pid-1522                             I  Restore complete.
2023-11-14 11:17:54.974  1522-2762  BackupManagerService    pid-1522                             V  [UserID:0] Released wakelock:*backup*-0-2762
2023-11-14 11:17:54.975 10154-10154 Configurab...ortService com.stevesoltys.seedvault            D  Service destroyed.
2023-11-14 11:17:55.054  1522-18904 RestoreSession          pid-1522                             D  endRestoreSession
2023-11-14 11:17:55.054  1522-2762  BackupManagerService    pid-1522                             V  [UserID:0] Clearing restore session and halting timeout
```

**Comment by grote** [comment]
Something isn't working right here. I got some error in the beginning which showed an error message in the UI and unlocked the FINISH button, however probably due to the new code, the restore continued and was actually doing stuff. 

Then this pattern keeps repeating over and over:

```ruby
2023-11-14 12:37:33.459 14334-14349 RestoreCoordinator      com.stevesoltys.seedvault            I  Start restore with [@pm@, com.android.rkpdapp, com.caydey.ffshare, com.gianlu.aria2android, com.android.traceur, org.woheller69.audio_analyzer_for_android]
...
2023-11-14 12:37:40.245 14334-14349 RestoreCoordinator      com.stevesoltys.seedvault            I  Start restore with [@pm@, org.xcsoar, deltazero.amarok.foss, com.android.settings, com.android.htmlviewer]
```

Somehow for each of those it is getting all restore sets, skipping over the one it can't decrypt. Why is it doing a `@pm@` restore for each set? Is this needed? What is causing it to re-load restore sets for each chunk?

**Comment by grote** [comment]
The error I got in the beginning may be a bug unrelated to this PR, us starting the restore session twice:

```ruby
2023-11-14 12:53:35.697 16771-16812 RestoreViewModel        com.stevesoltys.seedvault            D  Start InstallResult Flow
2023-11-14 12:53:35.713 16771-16812 RestoreViewModel        com.stevesoltys.seedvault            D  Starting new restore session to restore backup 1699970940126
2023-11-14 12:53:35.714  1522-1625  BackupManagerService    pid-1522                             V  [UserID:0] beginRestoreSession: pkg=null transport=com.stevesoltys.seedvault.transport.ConfigurableBackupTransport
2023-11-14 12:53:35.716 16771-16813 RestoreViewModel        com.stevesoltys.seedvault            D  Starting new restore session to restore backup 1699970940126
2023-11-14 12:53:35.717  1522-1560  BackupManagerService    pid-1522                             V  [UserID:0] beginRestoreSession: pkg=null transport=com.stevesoltys.seedvault.transport.ConfigurableBackupTransport
2023-11-14 12:53:35.717 16771-16814 RestoreViewModel        com.stevesoltys.seedvault            D  Completed InstallResult Flow
2023-11-14 12:53:35.751 16771-16771 Configurab...ortService com.stevesoltys.seedvault            D  Service created.
2023-11-14 12:53:35.753 16771-16771 Configurab...ortService com.stevesoltys.seedvault            D  Transport bound.
2023-11-14 12:53:35.757  1522-1625  BackupManagerService    pid-1522                             I  [UserID:0] Restore session requested but one already active
2023-11-14 12:53:35.760  1522-1560  BackupManagerService    pid-1522                             V  [UserID:0] Acquired wakelock:*backup*-0-2762
2023-11-14 12:53:35.760 16771-16812 RestoreViewModel        com.stevesoltys.seedvault            E  Error starting new session
                                                                                                    android.os.RemoteException: beginRestoreSessionForUser returned null
                                                                                                    	at com.stevesoltys.seedvault.restore.RestoreViewModel.getOrStartSession(RestoreViewModel.kt:132)
                                                                                                    	at com.stevesoltys.seedvault.restore.RestoreViewModel.startRestore(RestoreViewModel.kt:199)
                                                                                                    	at com.stevesoltys.seedvault.restore.RestoreViewModel.access$startRestore(RestoreViewModel.kt:74)
                                                                                                    	at com.stevesoltys.seedvault.restore.RestoreViewModel$onNextClickedAfterInstallingApps$1.invokeSuspend(RestoreViewModel.kt:183)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by grote** [comment]
For some reason, the backup metadata isn't cached, so in `RestoreCoordinator#startRestore()`, we end up calling `getAvailableMetadata()` for all chunks.

Given this and the fact that each chunks also does a `@pm@` restore, we should probably increase the chunk size as much as can be considered safe.

**Comment by grote** [comment]
The optimization for not having to re-fetch the backup metadata was to call `restoreCoordinator.beforeStartRestore(restorableBackup.backupMetadata)` which is only done once in this PR, not before each start.

@stevesoltys are you still following? So action items I see:

* increase chunk size to something large, maybe 100?
* ensure metadata is cached, probably by called `beforeStartRestore()` before each start
* figure out how to improve error reporting and enabling finish button fits into this multi-start approach
* find out why we (sometimes?) call `beginRestoreSession()` twice.

File: app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt (hunk 1 above)
Comment (stevesoltys) [reply app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt]: Confirmed that restore isn't working without this.

**Review by grote — APPROVED** [review]
Looks good now. There's still the issue that one chunk error will enable finish button and show error message before end and that restore session gets started twice, but we can resolve these in other MRs.
