### PR TITLE
Fix finishing RequireProvisioningActivity when provisioning is aborted

### LINKED ISSUE #352: Restore: Have to select "Don't restore" twice to actually exit since 12
The restore activity, launched either via SetupWizard, `*#*#RESTORE#*#*`, allows you to select "Don't Restore" (or hit the back button / use android back gesture)

On 11: Don't Restore / back exits
On 12: Don't Restore / back brings the same activity again.

line 1  03:07:50.000 launched activity from SetupWizard
line 7 03:07:52.024 tapped don't restore first time
line 14 03:07:54.504 tapped it second time

Partial log (`logcat | grep seedvault`):
```
12-30 03:07:50.000  1854 10406 I ActivityTaskManager: START u0 {act=com.stevesoltys.seedvault.RESTORE_BACKUP cmp=com.stevesoltys.seedvault/.restore.RestoreActivity (has extras)} from uid 1000
12-30 03:07:50.030 21392 21392 E SetupLibrary: [PartnerCustomizationLayout] Attribute sucUsePartnerResource not found in ComponentInfo{com.stevesoltys.seedvault/com.stevesoltys.seedvault.restore.RestoreActivity}
12-30 03:07:50.044  1854 10406 I ActivityTaskManager: START u0 {cmp=com.stevesoltys.seedvault/.ui.storage.StorageActivity (has extras)} from uid 10124
12-30 03:07:50.070 21392 21392 E SetupLibrary: [PartnerCustomizationLayout] Attribute sucUsePartnerResource not found in ComponentInfo{com.stevesoltys.seedvault/com.stevesoltys.seedvault.ui.storage.StorageActivity}
12-30 03:07:50.115  1854  2229 I ActivityTaskManager: Displayed com.stevesoltys.seedvault/.ui.storage.StorageActivity: +112ms

12-30 03:07:52.024  1854  2854 I ActivityTaskManager: START u0 {cmp=com.stevesoltys.seedvault/.ui.storage.StorageActivity (has extras)} from uid 10124
12-30 03:07:52.035 21392 21392 W com.stevesoltys.seedvault.ui.RequireProvisioningActivity: Error in activity result for requesting location
12-30 03:07:52.062 21392 21392 E SetupLibrary: [PartnerCustomizationLayout] Attribute sucUsePartnerResource not found in ComponentInfo{com.stevesoltys.seedvault/com.stevesoltys.seedvault.ui.storage.StorageActivity}
12-30 03:07:52.104  1854  2229 I ActivityTaskManager: Displayed com.stevesoltys.seedvault/.ui.storage.StorageActivity: +80ms
12-30 03:07:52.175  1854 10406 W InputManager-JNI: Input channel object 'c76d187 com.stevesoltys.seedvault/com.stevesoltys.seedvault.restore.RestoreActivity (client)' was disposed without first being removed with the input manager!
12-30 03:07:52.644  1854 11069 W InputManager-JNI: Input channel object '7e9c9d9 com.stevesoltys.seedvault/com.stevesoltys.seedvault.ui.storage.StorageActivity (client)' was disposed without first being removed with the input manager!

12-30 03:07:54.504  1854  3195 W InputManager-JNI: Input channel object '67a4744 com.stevesoltys.seedvault/com.stevesoltys.seedvault.ui.storage.StorageActivity (client)' was disposed without first being removed with the input manager!
```

### PR DESCRIPTION
**Pull request by grote**
On Android 11 this worked fine, but on Android 12 `onStart()` happens before activity results get delivered. We finish the activity when receiving a cancelled result. However, when `onStart()` gets called *before* we know the result, we relaunch an activity required for provisioning again instead of finishing.

Closes #352

### CODE REVIEW

File: app/src/main/java/com/stevesoltys/seedvault/SecretCodeReceiver.kt [hunk 1]
```diff
@@ -13,8 +13,7 @@ private const val RESTORE_SECRET_CODE = "7378673"
 class SecretCodeReceiver : BroadcastReceiver() {
 
     override fun onReceive(context: Context, intent: Intent) {
-        val host = intent.data.host
-        if (RESTORE_SECRET_CODE != host) return
+        if (intent.data?.host != RESTORE_SECRET_CODE) return
```
Comment (grote) [inline app/src/main/java/com/stevesoltys/seedvault/SecretCodeReceiver.kt:16]: This is an unrelated change, because I saw the lint warning about `intent.data` possibly being `null`.

**Review by chirayudesai — APPROVED** [review]

**Comment by chirayudesai** [comment]
Thanks!
