### PR TITLE
Auto-disable apps that cancel the entire backup

### LINKED ISSUE #491: Failure backing up a single app cancels the entire backup
Upstream issue, or perhaps by design, but I am noting it here for awareness if nothing else, since we may need to work around it.

If a single app misbehaves, crashes, or is otherwise displeased when the framework tries to retrieve its backup data, the framework will cancel the entire backup, spoiling it for all other apps and data.

Example I observed with Orbot (with D2D patch, but appears to occur in other circumstances too; see related):
```
W BackupManagerService: agentDisconnected: the backup agent for org.torproject.android died: cancel current operations
W PFTBT   : Full backup cancel of org.torproject.android
W PFTBT   : Backup cancelled. package=org.torproject.android, cancelAll=true
I PFTBT   : Full backup completed with status: -2003
```

See [UserBackupManagerService.java](https://cs.android.com/android/platform/superproject/+/android-13.0.0_r16:frameworks/base/services/backup/java/com/android/server/backup/UserBackupManagerService.java;l=3722-3736).

Related/same issue with `com.qualcomm.qcrilmsgtunnel`: #485

### PR DESCRIPTION
**Pull request by grote**
This can happen when the app process gets killed while its BackupAgent is running. There are several qcom apps in the wild that have this issue. These are DoSing our backups and are non-free, so we are defending ourselves against them.

Fixes #491

### CODE REVIEW

**Review by chirayudesai — DISMISSED** [review]

File: app/src/main/java/com/stevesoltys/seedvault/settings/SettingsManager.kt [hunk 1]
```diff
@@ -143,6 +143,15 @@ class SettingsManager(private val context: Context) {
 
     fun isBackupEnabled(packageName: String) = !blacklistedApps.contains(packageName)
 
+    /**
+     * Disables backup for an app. Similar to [onAppBackupStatusChanged].
+     */
+    fun disableBackup(packageName: String) {
+        if (blacklistedApps.add(packageName)) {
```
Comment (chirayudesai) [inline app/src/main/java/com/stevesoltys/seedvault/settings/SettingsManager.kt:173]: pedantic: can call it a denylist, that's the term used everywhere in AOSP now.

Comment (grote) [reply app/src/main/java/com/stevesoltys/seedvault/settings/SettingsManager.kt:173]: yep, but maybe in a separate MR. There's so many open MRs already and didn't want to do unnecessary changes here.

**Comment by theimpulson** [comment]
@grote this seems to have a merge conflict but seems good otherwise.

**Comment by stevesoltys** [comment]
Quite interested in how Google's backup service handles this one.

Regardless, still worth preventing this from happening in subsequent backups..

**Review by stevesoltys — DISMISSED** [review]

**Comment by grote** [comment]
> Quite interested in how Google's backup service handles this one.

Me too. Actually, with my test app https://gitlab.com/grote/backupagentcrasher we should be able to find out. Maybe @t-m-w still has a stock phone to try?

**Comment by grote** [comment]
just rebased and pushed

**Comment by t-m-w** [comment]
> > Quite interested in how Google's backup service handles this one.
> 
> Me too. Actually, with my test app https://gitlab.com/grote/backupagentcrasher we should be able to find out. Maybe @t-m-w still has a stock phone to try?

Stock fails on the crasher and the whole process is interrupted, just as with Seedvault. A toast appears with the message: "Couldn’t back up data. Try again later." 37 apps are backed up. Try again, same thing. If I uninstall the crasher and try again, there is no error, and 39 apps are backed up.

<details open><summary>Logcat snippet</summary>

```
I Backup  : [GmsBackupTransport] Attempt to do full backup on de.grobox.backupagentcrasher
I Backup  : [CryptoEnableCheck] Should not encrypt backups: device has no lock screen.
I Backup  : [FullBackupSession] Using unencrypted processor for de.grobox.backupagentcrasher
I Backup  : [FullBackupPackageWrapper] create full backup for : de.grobox.backupagentcrasher
I Backup  : [FullBackupPackageWrapper] Start scotty uploading.
I Backup  : [CryptoEnableCheck] Should not encrypt backups: device has no lock screen.
D BackupManagerService: [UserID:0] awaiting agent for ApplicationInfo{7d9ae74 de.grobox.backupagentcrasher}
E CrashingBackupAgent: onCreate: About to crash backup agent!
W BackupManagerService: agentDisconnected: the backup agent for de.grobox.backupagentcrasher died: cancel current operations
I BackupManagerService: [UserID:0] got agent null
W BackupManagerService: Unable to bind to full agent for de.grobox.backupagentcrasher
I Backup  : [GmsBackupTransport] Arbitrarily cancel full backup transfer.
W Backup  : [FullBackupPackageWrapper] Scotty transfer exception. fetf
I Backup  : [CryptoEnableCheck] Should not encrypt backups: device has no lock screen.
W PFTBT   : Backup cancelled. package=de.grobox.backupagentcrasher, cancelAll=true
I Backup  : [BackUpNowOperation] Backup done for de.grobox.backupagentcrasher, success: -2003
V BackupManagerService: [UserID:0] Released wakelock:*backup*-0-2982
W Backup  : [BackUpNowOperation] Backup cancelled for unknown reason.
I Backup  : [BackUpNowOperation] Running custom backups
W Backup  : [MmsAgent] No existing backup
W Backup  : aemi: Parse Proto Exception. - status:404
W Backup  : 	at aehg.c(:com.google.android.gms@241017038@24.10.17 (190400-617915183):157)
W Backup  : 	at aehg.b(:com.google.android.gms@241017038@24.10.17 (190400-617915183):18)
W Backup  : 	at aefy.c(:com.google.android.gms@241017038@24.10.17 (190400-617915183):16)
W Backup  : 	at agbg.f(:com.google.android.gms@241017038@24.10.17 (190400-617915183):217)
W Backup  : 	at agbj.run(:com.google.android.gms@241017038@24.10.17 (190400-617915183):230)
W Backup  : 	at alok.c(:com.google.android.gms@241017038@24.10.17 (190400-617915183):50)
W Backup  : 	at alok.run(:com.google.android.gms@241017038@24.10.17 (190400-617915183):76)
W Backup  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W Backup  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W Backup  : 	at alty.run(:com.google.android.gms@241017038@24.10.17 (190400-617915183):8)
W Backup  : 	at java.lang.Thread.run(Thread.java:1012)
I Backup  : [MmsAgent] Periodic backup progress update is scheduled.
I Backup  : [MmsAgent] Periodic backup progress update is shut down.
I Backup  : [BackUpNowOperation] Backup done for all packages, result code: 29001
```
</details>

**Comment by grote** [comment]
wow thanks for testing! backup DoS app here we come! Nice we are even going beyond play services here.

**Comment by stevesoltys** [comment]
Nice find. Wonder if we can report this upstream somehow.

**Comment by chirayudesai** [comment]
> Nice find. Wonder if we can report this upstream somehow.

issuetracker.google.com :)

**Review by chirayudesai — APPROVED** [review]
